apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
namePrefix: kustomize-

resources:
- deployment.yaml
- service.yaml

labels:
- pairs:
    app: myapp
    managed: argocd
  includeSelectors: true
  includeTemplates: true

replicas:
- name: myapp-deploy
  count: 3

images:
- name: ghcr.io/nobreak-labs/go-myweb
  newName: ghcr.io/nobreak-labs/go-myweb
  newTag: v1.0
