apiVersion: v1
kind: Service
metadata:
  name: myweb
  labels:
    app: myweb
spec:
  type: LoadBalancer
  selector:
    app: myweb
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
